### PR TITLE
Rebase jdk8 branch

### PR DESCRIPTION
**Pull request by zeroeightysix**
This PR rebases `jdk8` onto `master` and changes the github actions JDK version to 8.

Please note that the rebase leaves a non-linear commit history: let me know if you'd like a merge instead.

### CODE REVIEW

**Comment by elect86** [comment]
can you fix the CI?

**Comment by zeroeightysix** [comment]
I don't get why it's stalling. Works on my machine!

Can you try building?

**Comment by elect86** [comment]
Yep, you are right, it works on mine too

**Comment by elect86** [comment]
Let's see if jitpack can manage it through

**Pull request merged**
