### PR TITLE
remove .idea, .gitignore

### PR DESCRIPTION
**Pull request by Bixilon**
That folder should not belong in git

Spliite das mal in mehrere PRs

### CODE REVIEW

**Comment by elect86** [comment]
Are you sure?

I follow the Intellij guidelines in this regards

- https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
- https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

**Comment by Bixilon** [comment]
Oh, wow, did not know that. I am never commiting in into the repository.

But at least the .iml should go, that breaks things when cloning

**Comment by elect86** [comment]
It looks you are definitely right

> Items you may want to exclude from sharing:

    .iml files and .idea/modules.xml file for the Gradle or Maven based projects since these files will be generated on import
    
Mind undoing partially the commit to leave out `.iml` files?

**Comment by Bixilon** [comment]
Sure, that is not the problem.

But honestly if you look at the files...I only see, that it might be interesting to keep the run configurations but I don't really see a valueable part of the others, imho they get generated.

**Comment by elect86** [comment]
ah wait, now I got it.. the `.gitignore` is missing!

That's definitely an error, is this [one](https://github.com/kotlin-graphics/imgui/blob/master/.gitignore) fine for you? I'm using it across all the project and it's generated using the official guidelines

**Comment by Bixilon** [comment]
Yep, that one looks great.

**Comment by Bixilon** [comment]
Mostly updaded, left out the unneeded files

**Comment by elect86** [comment]
Thanks

**Pull request merged**
