### PR TITLE
Inlining refactor more

### PR DESCRIPTION
**Pull request by Bixilon**
4k changes...

Sadly it reverts #28, that conflicts with it.

Those are pertty much all all commits I made to improve performance.

Pretty much completes #30

### CODE REVIEW

**Comment by elect86** [comment]
I'm fine with this, the only thing is the reverting of #28, @kyay10 is it possible to find a solution right now?

Or are you ok with reverting that now (since it's not yet in use) and find a solution later on?

**Comment by kyay10** [comment]
Yes I'm absolutely fine with reverting that right now. I think I have a good idea of how to reach similar performance in the mp branch while still having those interfaces

**Comment by elect86** [comment]
CI fails, does it work on your machine, @Bixilon?

I cant test rn, I'll look into it later on

**Comment by Bixilon** [comment]
Fixed!

**Pull request merged**
