### PR TITLE
improve mat4 transforming performance

### PR DESCRIPTION
**Pull request by Bixilon**
Tests passing, its actually faster and allocates 0 memory now.

### CODE REVIEW

**Comment by elect86** [comment]
I wanted to change that sooner or later myself, thanks

**Comment by Bixilon** [comment]
How about a release? (also pushes to maven hopefully)

**Comment by elect86** [comment]
Personally I'd like to switch this to Multiplatform and then release.

I've already ported `unsigned` to MP, I just have to finish the last polishes and it's ready

Can you release it in the meanwhile? Which number would make sense to upgrade?

**Comment by Bixilon** [comment]
Can understand that. I could release but I don't want version numbers to differ from this repository and maven.

I mean it contains breaking changes, but build 12 would probably still fit?

**Comment by elect86** [comment]
ok, it makes sense actually, we can release it

I'll look into it, `build` is fine I guess?

**Comment by Bixilon** [comment]
For maven its actually enough if you push a tag I guess. If not, I will investigate it.

Am 22. Oktober 2023 23:07:23 MESZ schrieb Giuseppe Barbieri ***@***.***>:

**Comment by Bixilon** [comment]
Just published the tag `v0.9.9.1-build-12` which builds version `0.9.9.1-12`.  Not publishing it to mary though, no clue how that works.

Publishing to maven central failed, because it is not authorized. Have you stored the signing key and the credentials for in as a secret? I sent you them per email a while ago. I'll publish this release manually.

**Comment by elect86** [comment]
I still have theme somewhere

However, another issue I recall it now is that we have now maven central and mary, I wonder if we can automatically switch dependencies regarding where we are publishing (eg maven central shall fetch the maven central deps)

**Comment by Bixilon** [comment]
Sent it on 7/6/23.

That is actually a must have, otherwise things break and dependecies can not be resolved. I am not sure how to make it though. For glm it is really easy, there are no dependencies. kool and unsigned are runtime dependencies (i.e. add them if you need it). For projects that really require it, there needs to be a variable set that calles `implementation` in the dependecy section with the corresponding values. The other option is: Manipulating the generated pom.xml is farily easy, but changing the gradle build info (that is loaded my gradle and published too) is a hazard.

**Pull request merged**
